name: docker-multiarch

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: ${{ env.IMAGE_NAME }}
        registry: ${{ env.REGISTRY }}
        addLatest: true
        multiPlatform: true
        platform: linux/amd64,linux/arm64
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
